### ISSUE TITLE
Address field in centreon_storage.instances table 

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-broker#169]
Hello, 

Is there any particular reason why the "address" field in centreon_storage.instances is never updated/filled ? 

```
MariaDB [centreon_storage]> SELECT * FROM instances \G
*************************** 1. row ***************************
                 instance_id: 1
                        name: Central
[...]
                     address:
[...]
                     running: 1
                  start_time: 1519909527
                     version: 1.5.3
                     deleted: 0
                    outdated: 0
*************************** 2. row ***************************
                 instance_id: 2
                        name: Poller
                     address:
[...]
                     running: 1
                  start_time: 1519909526
                     version: 1.5.3
                     deleted: 0
                    outdated: 0
*************************** 3. row ***************************
                 instance_id: 3
                        name: Poller_Multiple
                   address:
 [...]
                     running: 1
                  start_time: 1502365705
                     version: 1.5.1
                     deleted: 0
                    outdated: 1
3 rows in set (0.00 sec)
```
